### ISSUE TITLE
Certs / CA in testbed (for keycloak)

### ISSUE THREAD

**Issue by garloff** [osism/testbed#1282]
I remember that we had discussed how to get trusted certificates in testbed deployments:
* testbeds would need to have a publicly resolvable domain name to request certs from Let's Encrypt (LE)
* keys of course need to be generated randomly upon deployment and can not be publicly stored in git
* we need to be wary of rate-limits for LE (50/domain/week)

According to http://docs.osism.de/testbed/deployment.html#tls-certificates-and-hostnames our current approach is a hardcoded domain name and we use a wildcard cert for *.testbed.osism.xyz.

When now trying to test federation with two keycloaks from two testbed installs, we find that they don't trust each other ...

We are trying to manually copy over trust anchors to enable those to trust each other, though we don't have it working yet.
(Hmmm, shouldn't two testbeds actually use the *same static custom CA* with wildcard certs for the same domain, so we have a different problem and maybe just not managed to establish trust for the custom CA in keycloak?)

However, I do wonder whether we could potentially have an easier solution to have an opt-in approach to actually get trusted certs using Let's Encrypt:
* Make the domain name configurable, so deployers can use their own, publicly resolvable DNS names
* Keys for certs would be randomly generated and the certs for these be requested from LE (via the normal http acme challenge)
* Ideally, we only need a small number of certs per testbed deployment (can we do with one?)

**Comment by berendt** [comment]
* the additional CA for Keycloak is unnecessary, will be fixed with #1308
* Letsencrypt does not always work everywhere and can lead to problems in the CI because of limits, so this was not an option and we opted for a custom CA
* Up to now, the testbed was always designed as a single instance, possibility to adapt the DNS names used (at least for the API endpoints) makes sense and should be done.

**Comment by reqa** [comment]
Ok, since this issue is still open, I'll re-use it to request an update for the certificate, because Keycloak rejects it (with a java exception) as non-RFC compliant:

```
Caused by: java.security.cert.CertificateParsingException: X.509 Certificate is incomplete: SubjectAlternativeName extension MUST be marked critical when subject field is empty
```

I guess the error message is referring to last sentence of the paragraph of https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.6

This issue is blocking us as it occurs when you want to do federation between SCS Keycloak instandes (e.g. also simply federating to a separate local Keycloak realm).

@JuanPTM did an experiment and manually created a new certificate locally in a testbed deployment so that
```
openssl x509 -text -in /opt/traefik/certificates/default.cert -noout | grep -C 2 -i alt
```
shows `X509v3 Subject Alternative Name: critical`. After deploying that and restarting traefik, the problem seems to have been solved. It would be great to also fix it in the default testbed deployments.

**Comment by berendt** [comment]
Since you have found a good workaround/solution to solve the problem, I think it does not block you anyway.

Please open a separate issue in the future as the requested adjustment has nothing to do with Kurt's original request. It gets lost very quickly that way.

**Comment by reqa** [comment]
Hmm, ok, will do, but why is this one then still open if my request then needs to be put elsewhere? Your repo, your rules.

**Comment by berendt** [comment]
We want to implement what you suggested as a workaround by regenerating the certificate once. Therefore, a separate issue, since what Kurt wants is not done with the addition of the SN.

**Comment by berendt** [comment]
That's done.
