### ISSUE TITLE
harbor.services.osism.tech/kolla/horizon:yoga unhealthy 

### ISSUE THREAD

**Issue by cah-link** [osism/testbed#1483]
Horizon returns 404 because Python3.10 could not be found

```
[client 192.168.16.11:51268] Target WSGI script not found or unable to stat: /var/lib/kolla/venv/lib/python3.10
```

```
root@testbed-node-1:/home/dragon# docker exec -it horizon bash
(horizon)[root@testbed-node-1 /]# ls /var/lib/kolla/venv/lib/python3.10
ls: cannot access '/var/lib/kolla/venv/lib/python3.10': No such file or directory
(horizon)[root@testbed-node-1 /]# ls /var/lib/kolla/venv/lib/
python3.8

```

**Comment by berendt** [comment]
Can you deploy Zed and see if you get the same error?

**Comment by berendt** [comment]
This is what currently happens when you roll out Yoga on Ubuntu 22.04. I had already prepared a patch for this, but it has not been applied yet. It will be fixed in a moment, then Yoga will also work on Ubuntu 22.04. We are currently only testing 20.04 and will only test Ubuntu 22.04 here in the testbed with the upcoming release.

**Comment by cah-link** [comment]
I see. Many Thanks!
