### ISSUE TITLE
Debug the Pluscloudopen deployment

### ISSUE THREAD

**Issue by berendt** [osism/testbed#912]
After the adjustment of Netplan, the networking does not work anymore. This causes the entire deployment to hang.

**Comment by berendt** [comment]
By @frosty-geek 

```
Hi,

we're experiencing unexpected behavior which leads to an unusable testbed while deploying to pluscloudopen. Currently this is under investigation and this issue is for collecting debugging information

errors which may be related to this issue are:

docker is unable to start container due to "dragon" user being unavaiable
chrony playbook is unable to install due to unknown reasons
swapping apt repos & pkg cache maybe?
why do we swap repos at all?
manager node loses network connectivity during ansible run & doesn't recover
is the config correct?
we've tried various terraform version ranging from 1.0.9 - 1.0.11, we will try to limit the tests to 1.0.9. further more we will try to reproduce the behavior with the commands used in the .github/workflows/daily-pluscloudopen.yml and will use the code from the main branch.
```

**Comment by Ferenc-** [comment]
My observation in the Pluscloudopen was more or less consistently that the manager node stopped responding over the network, shortly after reconfiguring the network, and afte logging `Removed slice` at the very end.

Deployment attempt 1:

```
[[0;32m  OK  [0m] Stopped [0;1;39mWait for Network to be Configured[0m.
         Stopping [0;1;39mNetwork Service[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mNetwork Service[0m.
         Starting [0;1;39mNetwork Service[0m...
[[0;32m  OK  [0m] Started [0;1;39mNetwork Service[0m.
         Stopping [0;1;39mUser Manager for UID 1000[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mUser Manager for UID 1000[0m.
         Stopping [0;1;39mUser Runtime Directory /run/user/1000[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mUser Runtime Directory /run/user/1000[0m.
[[0;32m  OK  [0m] Removed slice [0;1;39mUser Slice of UID 1000[0m.
         Stopping [0;1;39mUser Manager for UID 45000[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mUser Manager for UID 45000[0m.
         Stopping [0;1;39mUser Runtime Directory /run/user/45000[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mUser Runtime Directory /run/user/45000[0m.
[[0;32m  OK  [0m] Removed slice [0;1;39mUser Slice of UID 45000[0m.
```

Attempt 2:
```
[[0;32m  OK  [0m] Stopped [0;1;39mWait for Network to be Configured[0m.
         Stopping [0;1;39mNetwork Service[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mNetwork Service[0m.
         Starting [0;1;39mNetwork Service[0m...
[[0;32m  OK  [0m] Started [0;1;39mNetwork Service[0m.
[  901.132014] cloud-init[2348]: Monday 15 November 2021  07:19:14 +0000 (0:00:00.388)       0:04:17.115 *******
[  901.192107] cloud-init[2348]: TASK [osism.commons.cleanup : Include service tasks] ***************************
[  901.385619] cloud-init[2348]: included: /ansible/collections/ansible_collections/osism/commons/roles/cleanup/tasks/services.yml for testbed-node-0.osism.test
[  901.731384] cloud-init[2348]: Monday 15 November 2021  07:19:14 +0000 (0:00:00.599)       0:04:17.714 *******
[  901.807342] cloud-init[2348]: TASK [osism.commons.cleanup : Gather variables for each operating system] ******
[  901.809434] cloud-init[2348]: ok: [testbed-node-0.osism.test]
[  902.269712] cloud-init[2348]: Monday 15 November 2021  07:19:15 +0000 (0:00:00.537)       0:04:18.252 *******
[  902.345529] cloud-init[2348]: TASK [osism.commons.cleanup : Cleanup services] ********************************
[  902.347998] cloud-init[2348]: skipping: [testbed-node-0.osism.test] => (item=NetworkManager)
[  902.351358] cloud-init[2348]: skipping: [testbed-node-0.osism.test] => (item=iscsid)
[  902.362014] cloud-init[2348]: skipping: [testbed-node-0.osism.test] => (item=lxcfs)
[  902.367299] cloud-init[2348]: skipping: [testbed-node-0.osism.test] => (item=nscd)
[  902.375553] cloud-init[2348]: skipping: [testbed-node-0.osism.test] => (item=ntp)
         Stopping [0;1;39mUser Manager for UID 1000[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mUser Manager for UID 1000[0m.
         Stopping [0;1;39mUser Runtime Directory /run/user/1000[0m...
[[0;32m  OK  [0m] Stopped [0;1;39mUser Runtime Directory /run/user/1000[0m.
[[0;32m  OK  [0m] Removed slice [0;1;39mUser Slice of UID 1000[0m.
```

I assume this falls into the aforementioned `manager node loses network connectivity during ansible run & doesn't recover` category. Please correct me if I am wrong.

**Comment by matfechner** [comment]
Hi @Ferenc-  
we see also this  issue,
this  happens when networkd-dispatch reconfigure  the  network configuration,
i have one testbed which is  working  and another which have the same  issue
perhaps we've a solutions today or tomorrow

**Comment by plus-cstelter** [comment]
The moment the task "osism.commons.cleanup : Cleanup services" restarts the network there is no config in /etc/netplan or /etc/network/interfaces* so the testbed-manager loses his IP in the net-testbed-management network (192.168.16.5).

```
TASK [osism.services.smartd : Start/enable smartd service] *********************
ok: [testbed-node-2.osism.test]

TASK [osism.commons.cleanup : Cleanup services] ********************************
skipping: [testbed-manager.osism.test] => (item=NetworkManager)
skipping: [testbed-manager.osism.test] => (item=iscsid)
skipping: [testbed-manager.osism.test] => (item=lxcfs)
skipping: [testbed-manager.osism.test] => (item=nscd)
skipping: [testbed-manager.osism.test] => (item=ntp)
Monday 15 November 2021  13:33:00 +0000 (0:00:00.588)       0:10:40.632 *******
changed: [testbed-manager.osism.test] => (item=networkd-dispatcher)
client_loop: send disconnect: Broken pipe
```
State shortly after login into the console:

![Screenshot 2021-11-15 at 14 41 25](https://user-images.githubusercontent.com/62995499/141791866-3aa403ed-6a21-4946-bc1f-5e6697cb697d.png)

If you run a "dhclient ens3" manually, you get the address again.

**Comment by berendt** [comment]
Then it is probably related to that. I'll take ``systemd-networkd`` out for a moment so you can do a test.

```
cleanup_services_extra:
  - NetworkManager
  - iscsid
  - lxcfs
  - nscd
  - ntp
  - networkd-dispatcher
  - systemd-networkd
```

**Comment by frosty-geek** [comment]
0a29ea0cae230ea7d952c65aa1138471f4dc87fe looks alot better

[0a29ea0cae230ea7d952c65aa1138471f4dc87fe-cloud-init-output.log](https://github.com/osism/testbed/files/7544684/0a29ea0cae230ea7d952c65aa1138471f4dc87fe-cloud-init-output.log)

**Comment by plus-cstelter** [comment]
I could deploy (via make deploy-openstack) which installed all services. But when I try to login via horizon I get an:

```
[Tue Nov 16 16:43:19.337489 2021] [wsgi:error] [pid 66:tid 140612963956480] [remote 192.168.16.12:38996] Attempted scope to domain Default failed, will attempt to scope to another domain.
[Tue Nov 16 16:43:19.432768 2021] [wsgi:error] [pid 66:tid 140612963956480] [remote 192.168.16.12:38996] Login successful for user "admin" using domain "Default", remote address 192.168.16.12.
[Tue Nov 16 16:43:20.748405 2021] [wsgi:error] [pid 66:tid 140612963956480] [remote 192.168.16.12:38996] Call to list enabled services failed. This is likely due to a problem communicating with the Neutron endpoint. RBAC Policies panel will not be displayed.
[Tue Nov 16 16:43:21.649318 2021] [wsgi:error] [pid 66:tid 140612963956480] [remote 192.168.16.12:38996] Forbidden: /project/
[Tue Nov 16 16:43:26.814018 2021] [wsgi:error] [pid 65:tid 140612963956480] [remote 192.168.16.12:39566] Call to list enabled services failed. This is likely due to a problem communicating with the Neutron endpoint. RBAC Policies panel will not be displayed.
[Tue Nov 16 16:43:27.209621 2021] [wsgi:error] [pid 65:tid 140612963956480] [remote 192.168.16.12:39566] Forbidden: /project/
```
I will take a look into the cloud-init-output.log if I can find anything.

**Comment by frosty-geek** [comment]
Hi @berendt 

I think we still have an MTU Issue which only seems to affects pluscloudopen due to our current limit of mtu 1442 within the Openstack VMs.

Can you please confirm or deny whether betacloud aswell as citynetworks run on mtu 1500 for the Openstack VMs?

since the default docker network docker0 is not used adding the mtu keyword to the /etc/docker/daemon.json has no effect on those "custom" docker networks (or at least i don't know how to fix it). 

So the changes from https://github.com/osism/testbed/commit/6062dddf22c13f498631caeace7a7630888bacf2 don't trickle down to the docker containers running in "custom" docker networks.

I noticed the mtu 1500 while trying to hunt down why the heck https://github.com/osism/testbed/blob/3f4dcb6225cdbc2ba360af2fb584c99c94749249/environments/openstack/playbook-bootstrap-basic.yml#L222 was unable to download the latest cirros image.

![image](https://user-images.githubusercontent.com/2196917/145118639-3f80fa2f-07c7-4c38-b81b-8df9c2b4221f.png)

-------------cut--------------
root@testbed-manager:/var/lib/docker# cp /bin/busybox /var/lib/docker/volumes/manager_interface/_data/
root@testbed-manager:/var/lib/docker# docker exec -it manager_kolla-ansible_1 /interface/busybox ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
102: eth0@if103: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 02:42:ac:1f:65:0a brd ff:ff:ff:ff:ff:ff


root@testbed-manager:~# cat /etc/docker/daemon.json; ip -o link show; docker network ls
{
    "mtu": 1442,
    "bridge": "none",
    "debug": false,
    "experimental": false,
    "hosts": ["unix:///var/run/docker.sock"],
    "insecure-registries": [],
    "ipv6": false,
    "live-restore": true,
    "log-driver": "json-file",
    "log-level": "info",
    "log-opts": {
      "max-file": "3", 
      "max-size": "10m"
    },
    "registry-mirrors": [],
    "storage-driver": "overlay2",
    "default-runtime": "runc"
}
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc fq_codel state UP mode DEFAULT group default qlen 1000\    link/ether fa:16:3e:2c:ff:14 brd ff:ff:ff:ff:ff:ff
3: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1320 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\    link/none 
4: vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1350 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\    link/ether 0e:df:af:53:7b:66 brd ff:ff:ff:ff:ff:ff
5: br-3e86ee0c2536: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:7d:eb:75:14 brd ff:ff:ff:ff:ff:ff
6: br-3607e4bf0041: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:8f:d1:e8:b8 brd ff:ff:ff:ff:ff:ff
7: br-3e7646b50e85: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:06:ca:bb:c9 brd ff:ff:ff:ff:ff:ff
8: br-58eb926b021c: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:5f:0c:dd:ec brd ff:ff:ff:ff:ff:ff
9: br-5b96886b53c1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:df:28:f5:a9 brd ff:ff:ff:ff:ff:ff
10: br-6a6a3bc6ff86: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:ea:13:e5:39 brd ff:ff:ff:ff:ff:ff
11: br-6b3aa101575f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:4d:b8:b9:76 brd ff:ff:ff:ff:ff:ff
12: br-9770998e0b72: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:b5:fb:5e:1e brd ff:ff:ff:ff:ff:ff
13: br-e74a6d4f6299: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default \    link/ether 02:42:7f:f5:86:a7 brd ff:ff:ff:ff:ff:ff
15: veth057df10@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-e74a6d4f6299 state UP mode DEFAULT group default \    link/ether 8a:42:fb:5c:d4:7a brd ff:ff:ff:ff:ff:ff link-netnsid 0
61: veth8717d15@if60: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-9770998e0b72 state UP mode DEFAULT group default \    link/ether 02:12:87:52:b8:0b brd ff:ff:ff:ff:ff:ff link-netnsid 1
63: veth680e040@if62: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-5b96886b53c1 state UP mode DEFAULT group default \    link/ether 62:8f:b3:25:90:e2 brd ff:ff:ff:ff:ff:ff link-netnsid 2
65: vethd0663e1@if64: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6a6a3bc6ff86 state UP mode DEFAULT group default \    link/ether 1e:f3:d7:fe:78:8e brd ff:ff:ff:ff:ff:ff link-netnsid 3
67: veth1537d44@if66: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3e86ee0c2536 state UP mode DEFAULT group default \    link/ether a6:33:69:7f:52:f4 brd ff:ff:ff:ff:ff:ff link-netnsid 4
69: veth3d326cf@if68: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3607e4bf0041 state UP mode DEFAULT group default \    link/ether 0a:97:d9:11:f0:55 brd ff:ff:ff:ff:ff:ff link-netnsid 5
71: veth8030591@if70: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-58eb926b021c state UP mode DEFAULT group default \    link/ether 6a:e3:bc:0c:f5:27 brd ff:ff:ff:ff:ff:ff link-netnsid 7
73: veth67c06c7@if72: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-58eb926b021c state UP mode DEFAULT group default \    link/ether 9a:e1:44:f0:4f:31 brd ff:ff:ff:ff:ff:ff link-netnsid 8
75: veth385a48a@if74: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3e7646b50e85 state UP mode DEFAULT group default \    link/ether b6:fe:c1:73:12:e8 brd ff:ff:ff:ff:ff:ff link-netnsid 9
77: veth9b0d8c7@if76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3e7646b50e85 state UP mode DEFAULT group default \    link/ether 6a:b1:86:b1:52:23 brd ff:ff:ff:ff:ff:ff link-netnsid 6
79: veth6eebd81@if78: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3e86ee0c2536 state UP mode DEFAULT group default \    link/ether 02:5b:0a:ef:77:58 brd ff:ff:ff:ff:ff:ff link-netnsid 11
81: veth4ca529c@if80: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether 76:9e:89:be:cd:cd brd ff:ff:ff:ff:ff:ff link-netnsid 12
83: veth4a469d0@if82: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether f2:e2:05:86:6b:fd brd ff:ff:ff:ff:ff:ff link-netnsid 10
85: veth809d59c@if84: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether 6a:9e:51:80:85:ec brd ff:ff:ff:ff:ff:ff link-netnsid 13
87: vethc443c9c@if86: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether de:0c:7b:16:88:40 brd ff:ff:ff:ff:ff:ff link-netnsid 14
89: vethc8ded55@if88: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether 92:ac:fa:83:30:15 brd ff:ff:ff:ff:ff:ff link-netnsid 17
91: veth2c4dc08@if90: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether 7e:fa:eb:f9:f6:30 brd ff:ff:ff:ff:ff:ff link-netnsid 15
93: veth8bb9f2e@if92: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-58eb926b021c state UP mode DEFAULT group default \    link/ether 82:cc:eb:f2:cb:2b brd ff:ff:ff:ff:ff:ff link-netnsid 16
95: veth5b1ae4e@if94: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3e7646b50e85 state UP mode DEFAULT group default \    link/ether 3a:92:ff:ee:65:f2 brd ff:ff:ff:ff:ff:ff link-netnsid 18
97: veth64e3b5e@if96: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether 3e:b5:2b:22:d1:39 brd ff:ff:ff:ff:ff:ff link-netnsid 21
99: veth03c5c1c@if98: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-3e7646b50e85 state UP mode DEFAULT group default \    link/ether 6e:ef:fa:02:ef:5d brd ff:ff:ff:ff:ff:ff link-netnsid 22
101: veth2c02868@if100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether e2:d3:46:3b:6b:47 brd ff:ff:ff:ff:ff:ff link-netnsid 20
103: veth4f95445@if102: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6b3aa101575f state UP mode DEFAULT group default \    link/ether 02:00:f9:e4:17:f6 brd ff:ff:ff:ff:ff:ff link-netnsid 23
NETWORK ID     NAME                               DRIVER    SCOPE
3607e4bf0041   cephclient_default                 bridge    local
9770998e0b72   homer_default                      bridge    local
c9b4e49e112c   host                               host      local
3e86ee0c2536   keycloak_default                   bridge    local
6b3aa101575f   manager_default                    bridge    local
3e7646b50e85   netbox_default                     bridge    local
4d55ccd94a0b   none                               null      local
e74a6d4f6299   openstack_health_monitor_default   bridge    local
6a6a3bc6ff86   openstackclient_default            bridge    local
58eb926b021c   patchman_default                   bridge    local
5b96886b53c1   phpmyadmin_default                 bridge    local
-------------cut--------------

**Comment by frosty-geek** [comment]
I can confirm that #494  + #974 fixed all interfaces on the manager and ARA reports no errors when doing a "deploy-full", but there are still interfaces created on the testbed-node-X systems which have an MTU of 1500.

---------------cut-----------------
dragon@testbed-node-0:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:e9:32:8b brd ff:ff:ff:ff:ff:ff
3: vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1350 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether ee:5c:b1:78:ca:9c brd ff:ff:ff:ff:ff:ff
4: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 6a:f5:ea:9d:49:bc brd ff:ff:ff:ff:ff:ff
5: br-ex: <BROADCAST,MULTICAST> mtu 1350 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether b2:5a:07:d9:8a:48 brd ff:ff:ff:ff:ff:ff
6: br-int: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether be:6a:74:d0:a8:4b brd ff:ff:ff:ff:ff:ff
7: genev_sys_6081: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether a2:cc:8f:7c:1f:98 brd ff:ff:ff:ff:ff:ff
8: ohm0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1342 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:6d:41:17 brd ff:ff:ff:ff:ff:ff
9: tap1b175455-10@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether 4e:05:28:1e:d1:5c brd ff:ff:ff:ff:ff:ff link-netns ovnmeta-1b175455-147a-40d4-a23a-c50a379381e6
10: br-3c10cc04bc75: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:94:7b:36:e7 brd ff:ff:ff:ff:ff:ff
14: veth5086394@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master br-3c10cc04bc75 state UP mode DEFAULT group default 
    link/ether b2:7d:0f:66:4d:20 brd ff:ff:ff:ff:ff:ff link-netnsid 1
---------------cut-----------------

**Comment by frosty-geek** [comment]
@berendt @osfrickler maybe we can re-open this Issue
